version: '3.8'
services:
  postgres:
    build: .
    container_name: meshos-postgres
    environment:
      POSTGRES_DB: meshos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 5646
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    networks:
      - meshos-network

  # Simple Iceberg Rest Catalog (standalone)
  iceberg-rest:
    image: tabulario/iceberg-rest:0.9.0
    container_name: iceberg-rest
    ports:
      - "8181:8181"
    environment:
      - CATALOG_WAREHOUSE=file:///tmp/warehouse
      - CATALOG_IO__IMPL=org.apache.iceberg.hadoop.HadoopFileIO
    volumes:
      - iceberg_warehouse:/tmp/warehouse
    networks:
      - meshos-network

  # Add Spark for SQL queries
  spark:
    image: apache/spark:3.4.0-scala2.12-java11-python3-ubuntu
    container_name: spark-sql
    ports:
      - "8080:8080"  # Spark Master Web UI
      - "4040:4040"  # Spark Application Web UI
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
    volumes:
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - iceberg_warehouse:/tmp/warehouse
    networks:
      - meshos-network
    depends_on:
      - iceberg-rest
    command: >
      bash -c "
      /opt/spark/bin/spark-sql 
      --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
      --conf spark.sql.catalog.rest=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.rest.type=rest
      --conf spark.sql.catalog.rest.uri=http://iceberg-rest:8181
      --packages org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.4.0
      "

volumes:
  postgres_data:
  iceberg_warehouse:

networks:
  meshos-network:
    external: true
